<a href="https://colab.research.google.com/github/LiliiaCheban/data-and-python/blob/main/Interrogating_the_dataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercise 1 - get the data, look at first 10 records

In [ ]:
import pandas as pd
url='https://github.com/futureCodersSE/working-with-data/blob/main/Data%20sets/public_use-talent-migration.xlsx?raw=true'
df=pd.read_excel(url,sheet_name="Industry Migration")
df
df.head(10)

,country_code,country_name,wb_income,wb_region,isic_section_index,isic_section_name,industry_id,industry_name,net_per_10K_2015,net_per_10K_2016,net_per_10K_2017,net_per_10K_2018,net_per_10K_2019
0,ae,United Arab Emirates,High income,Middle East & North Africa,C,Manufacturing,1,Defense & Space,378.74,127.94,8.20,68.51,49.55
1,ae,United Arab Emirates,High income,Middle East & North Africa,J,Information and communication,3,Computer Hardware,100.97,358.14,112.98,149.57,182.22
2,ae,United Arab Emirates,High income,Middle East & North Africa,J,Information and communication,4,Computer Software,1079.36,848.15,596.48,409.18,407.41
3,ae,United Arab Emirates,High income,Middle East & North Africa,J,Information and communication,5,Computer Networking,401.46,447.39,163.99,236.69,188.07
4,ae,United Arab Emirates,High income,Middle East & North Africa,J,Information and communication,6,Internet,1840.33,1368.42,877.71,852.39,519.40
5,ae,United Arab Emirates,High income,Middle East & North Africa,J,Information and communication,8,Telecommunications,676.91,676.11,365.96,283.59,281.91
6,ae,United Arab Emirates,High income,Middle East & North Africa,M,Professional scientific and technical activities,9,Law Practice,694.50,529.50,362.83,356.56,147.83
7,ae,United Arab Emirates,High income,Middle East & North Africa,M,Professional scientific and technical activities,10,Legal Services,661.10,665.65,462.30,475.62,255.21
8,ae,United Arab Emirates,High income,Middle East & North Africa,M,Professional scientific and technical activities,11,Management Consulting,982.85,694.25,520.28,574.60,406.03
9,ae,United Arab Emirates,High income,Middle East & North Africa,M,Professional scientific and technical activities,12,Biotechnology,1230.17,846.28,500.77,205.78,513.23

Exercise 2 - display just two columns

In [5]:
import pandas as pd
url='https://github.com/futureCodersSE/working-with-data/blob/main/Data%20sets/public_use-talent-migration.xlsx?raw=true'
df=pd.read_excel(url,sheet_name="Industry Migration")
df
df[[country_code,',',industry_name]]

NameError: ignored